require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComplainsController do

  # This should return the minimal set of attributes required to create a valid
  # Complain. As you add validations to Complain, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComplainsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all complains as @complains" do
      complain = Complain.create! valid_attributes
      get :index, {}, valid_session
      assigns(:complains).should eq([complain])
    end
  end

  describe "GET show" do
    it "assigns the requested complain as @complain" do
      complain = Complain.create! valid_attributes
      get :show, {:id => complain.to_param}, valid_session
      assigns(:complain).should eq(complain)
    end
  end

  describe "GET new" do
    it "assigns a new complain as @complain" do
      get :new, {}, valid_session
      assigns(:complain).should be_a_new(Complain)
    end
  end

  describe "GET edit" do
    it "assigns the requested complain as @complain" do
      complain = Complain.create! valid_attributes
      get :edit, {:id => complain.to_param}, valid_session
      assigns(:complain).should eq(complain)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Complain" do
        expect {
          post :create, {:complain => valid_attributes}, valid_session
        }.to change(Complain, :count).by(1)
      end

      it "assigns a newly created complain as @complain" do
        post :create, {:complain => valid_attributes}, valid_session
        assigns(:complain).should be_a(Complain)
        assigns(:complain).should be_persisted
      end

      it "redirects to the created complain" do
        post :create, {:complain => valid_attributes}, valid_session
        response.should redirect_to(Complain.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved complain as @complain" do
        # Trigger the behavior that occurs when invalid params are submitted
        Complain.any_instance.stub(:save).and_return(false)
        post :create, {:complain => {}}, valid_session
        assigns(:complain).should be_a_new(Complain)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Complain.any_instance.stub(:save).and_return(false)
        post :create, {:complain => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested complain" do
        complain = Complain.create! valid_attributes
        # Assuming there are no other complains in the database, this
        # specifies that the Complain created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Complain.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => complain.to_param, :complain => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested complain as @complain" do
        complain = Complain.create! valid_attributes
        put :update, {:id => complain.to_param, :complain => valid_attributes}, valid_session
        assigns(:complain).should eq(complain)
      end

      it "redirects to the complain" do
        complain = Complain.create! valid_attributes
        put :update, {:id => complain.to_param, :complain => valid_attributes}, valid_session
        response.should redirect_to(complain)
      end
    end

    describe "with invalid params" do
      it "assigns the complain as @complain" do
        complain = Complain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Complain.any_instance.stub(:save).and_return(false)
        put :update, {:id => complain.to_param, :complain => {}}, valid_session
        assigns(:complain).should eq(complain)
      end

      it "re-renders the 'edit' template" do
        complain = Complain.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Complain.any_instance.stub(:save).and_return(false)
        put :update, {:id => complain.to_param, :complain => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested complain" do
      complain = Complain.create! valid_attributes
      expect {
        delete :destroy, {:id => complain.to_param}, valid_session
      }.to change(Complain, :count).by(-1)
    end

    it "redirects to the complains list" do
      complain = Complain.create! valid_attributes
      delete :destroy, {:id => complain.to_param}, valid_session
      response.should redirect_to(complains_url)
    end
  end

end
